apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraback-deployment
  namespace: app
  labels:
    app: infraback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infraback
  template:
    metadata:
      labels:
        app: infraback
    spec:
      containers:
        - name: infraback
          image: luannv67922/infraback:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: "postgres-service.dbcenter.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "infradb"
            - name: POSTGRES_USER
              value: "infrauser"
            - name: POSTGRES_PASSWORD
              value: "123456"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: infraback-service
  namespace: app
spec:
  selector:
    app: infraback
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 32001
  type: NodePort
