apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-web-deployment
  namespace: app
  labels:
    app: infra-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-web
  template:
    metadata:
      labels:
        app: infra-web
    spec:
      containers:
        - name: infra-web
          image: luannv67922/infraweb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: infra-web-service
  namespace: app
spec:
  selector:
    app: infra-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32003
  type: NodePort
