apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-php
  labels:
    app: frontend-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-php
  template:
    metadata:
      labels:
        app: frontend-php
    spec:
      containers:
        - name: frontend
          image: luannv67922/frontend-php:latest  # <-- build & push trước
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-php-service
spec:
  type: NodePort
  selector:
    app: frontend-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32002   # <-- NodePort bạn có thể thay đổi
