apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrafront-deployment
  namespace: app
  labels:
    app: infrafront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infrafront
  template:
    metadata:
      labels:
        app: infrafront
    spec:
      containers:
        - name: infrafront
          image: YOUR_DOCKERHUB_USER/infrafront:latest  # replace
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: infrafront-service
  namespace: app
spec:
  selector:
    app: infrafront
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32000
  type: NodePort
